language: node_js

env:
  - CXX=g++-4.8

node_js:
  - '13.2.0'
  - '12.13.1'
  - '10.17.0'
  - '8.16.2'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

notifications:
  email: false

sudo: false

before_install:
  - $CXX --version
